const questions = [
    {
        question: 'What is the capital of Chile?',
        a: 'Lisbona',
        b: 'Tokio',
        c: 'Santiago',
        d: 'Warsaw',
        answer: 'Santiago',
    },{
        question: 'What is the highest mountain in Britain?',
        a: 'Ben Nevis',
        b: 'Rysy',
        c: 'K2',
        d: 'Mount Rushmore',
        answer: 'Ben Nevis',
    },{
        question: 'What is the smallest country in the world?',
        a: 'Belgium',
        b: 'Russia',
        c: 'San Marino',
        d: 'Vatican City',
        answer: 'Vatican City',
    },{
        question: 'Alberta is a province of which country?',
        a: 'USA',
        b: 'Canada',
        c: 'Norway',
        d: 'UK',
        answer: 'Canada',
    },{
        question: 'How many countries still have the shilling as currency?',
        a: 'Two',
        b: 'Three',
        c: 'Four',
        d: 'Five',
        answer: 'Four',
    },{
        question: 'Which is the only vowel not used as the first letter in a US State?',
        a: 'E',
        b: 'A',
        c: 'I',
        d: 'O',
        answer: 'E',
    },{
        question: 'What is the largest country in the world?',
        a: 'Australia',
        b: 'Brasil',
        c: 'Russia',
        d: 'USA',
        answer: 'Russia',
    },{
        question: 'Where would you find the River Thames?',
        a: 'London',
        b: 'Paris',
        c: 'Cairo',
        d: 'Chicago',
        answer: 'London',
    },{
        question: 'What is the hottest continent on Earth?',
        a: 'Australia',
        b: 'Europe',
        c: 'Asia',
        d: 'Africa',
        answer: 'Africa',
    },{
        question: 'What is the longest river in the world?',
        a: 'Wisla',
        b: 'Nile',
        c: 'Amazon',
        d: 'Thames',
        answer: 'Nile',
    }
]